### PR TITLE
Update Feature/451 notification visibility branch for #461

### PR DESCRIPTION
**Pull request by jerclarke**
For this I started with `feature/451-notification-visibility` branch, merged in `master`, then fixed a small conflict and commited. 

I then added a commit with my fix described [in a comment on #461](https://github.com/Automattic/Edit-Flow/pull/461#issuecomment-437193887)

Now I'm trying to submit a PR. This is all part of #265 

If this is wrong, please tell me what I should have done instead. Thank you.

### CODE REVIEW

**Comment by WPprodigy** [comment]
This could cause some issues merging this way, but not really your fault with making this change given the current state of PRs.

I agree with your comment in another ticket about creating a feature branch to get all these things merged together since they are so interdependent. Then you can push a PR against the branch.

**Comment by jerclarke** [comment]
Thanks @WPprodigy 

So I'll wait for further instructions WRT all this I guess.

cc/ @sboisvert

**Comment by rinatkhaziev** [comment]
Hi @jerclarke, thanks for your work, however, merging this in might be a huge ordeal which none of us needs to go through :)

Do you mind opening a new PR and abandoning this one? I believe I've merged all the other work in master already.

**Comment by jerclarke** [comment]
Working on this today, takes awhile just to remind myself what I was doing a month ago. Can't guarantee anything ready, that's a pretty tight deadline.

**Comment by rinatkhaziev** [comment]
@jerclarke no worries, we’re not releasing it this week, it was an
ambitious plan. Not going to shoot ourselves in the foot over a holiday
release :)

**Pull request closed without merging**
