### PR TITLE
Update user-groups.php

### PR DESCRIPTION
**Pull request by paulabbott**
This was throwing an error when users edited there profile via a custom front end user profile page.

### CODE REVIEW

**Comment by cojennin** [comment]
Looks good. Just a few spacing issues that need cleanup.

There's an extra space [here](https://github.com/Automattic/Edit-Flow/pull/283/files#diff-4e59b27536156258f08652c20b30bed0R644) and [here](https://github.com/Automattic/Edit-Flow/pull/283/files#diff-4e59b27536156258f08652c20b30bed0R691) in front of the `if` that can be removed. 

There should also be a space before and after each parenthesis in both of those `if` statements.

Once that's fixed up should be able to merge this in.

**Comment by cojennin** [comment]
Just following up on this PR. Any chance you'll be able to make some tweaks to this PR?

**Comment by paulabbott** [comment]
hows this?

**Comment by paulabbott** [comment]
Hello can you accept or close this pull request, thanks.

**Comment by cojennin** [comment]
Ah, missed this, apologies! Looks good (test failure is unrelated). Merging, thanks!

**Comment by amit0001** [comment]
Ran into this bug on the latest version. I verified I have this code, but still got the error:

Call to undefined function get_current_screen() in /var/www/html/wp-content/plugins/edit-flow/modules/user-groups/user-groups.php on line 691

I have a custom user profile screen on the front end, which is probably why this function is not defined. Still a WP noob :)

**Comment by philipjohn** [comment]
@amit0001 Given this one is closed, could I ask you to open a new issue please, with precise steps to reproduce? Before you do so, could you also check whether you still get this error without any customisations, just to be sure it's not caused by any custom code? Thanks!

**Pull request merged**
