### PR TITLE
Support adding non-post data into days of calendar #417

### PR DESCRIPTION
**Pull request by cklosowski**
Initial thoughts/proposal for #417

### CODE REVIEW

**Comment by cklosowski** [comment]
This would allow something like this to be used:
```
<?php

function ck_add_shares_calendar_data( $items, $week_single_date ) {

	$items[] = array(
		'type' => 'share',
		'content' => 'Testing',
	);

	return $items;
}
add_filter( 'ef_calendar_posts_for_week', 'ck_add_shares_calendar_data', 10, 2 );

function ck_add_shares_to_ef_calendar( $output, $num, $post ) {
	if ( $post['type'] === 'share' ) {
		$output = $post['content'];
	}
	return $output;
}
add_filter( 'ef_calendar_single_date_item', 'ck_add_shares_to_ef_calendar', 10, 3 );
```

Which results in the ability to add something similar to:
screen shot 2018-01-22 at 11 15 56 pm

this is devoid of styling at the moment, but is just a proposal to see if it would be considered.

**Comment by justnorris** [comment]
Strict Yoda statements FTW.

Any thoughts on changing `pre_ef_***` to `ef_pre_***`? Would that make the naming/prefixes more consistent?

**Comment by justnorris** [comment]
Alright, this looks like good to go. 

@sboisvert - any thoughts?

**Comment by cklosowski** [comment]
Any updates here @justnorris @sboisvert ? Need anything else from me to get this :+1:'d and merged?

**Comment by sboisvert** [comment]
@philipjohn this looks good from my end, if you're 👍 then let's merge it :)

**Comment by rinatkhaziev** [comment]
@cklosowski @sboisvert @philipjohn 

I have two notes here: 

```
foreach ( $week_posts[$week_single_date] as $num => $post ){
  $output = apply_filters( 'ef_pre_calendar_single_date_item_html', false, $this, $num, $post, $week_single_date );
  if ( false === $output ) {
    $output = $this->generate_post_li_html( $post, $week_single_date, $num );
  }
  echo $output;
}
```
While this code is working, I feel like there's a room for improvement clarity-wise - `$output` is clearly intended to be a string, yet the initial value is false and the consequent check is also against a boolean. I propose to change the initial value for filter to an empty string `''` and then change the check to 
```
// either 
if ( ! $output ) {
// or 
if ( '' === $output ) {
```
This will help to better communicate the intent. 

Another suggestion regarding that piece is that it can be reduced to a ternary:

```echo $output ?:  $this->generate_post_li_html( $post, $week_single_date, $num );```

The other note is Coding Standards violations around spacing array `When referring to array items, only include a space around the index if it is a variable` and a missing space before the opening brace in foreach : https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage . I realize it might sound nit-picky and the plugin is ridden with CS inconsitencies, we should probably try avoiding adding up to the problem :)

**Pull request merged**
