### PR TITLE
Fix failing GitHub e2e tests

### PR DESCRIPTION
**Pull request by alecgeatches**
As a first step for modernization, this PR:

- Fixes end-to-end tests. Most of these failures were due to old CSS selectors that no longer work with modern WordPress admin components. All existing end to end tests should now pass.
- Updates the lowest supported PHP version to `7.4`, and removes testing for lower versions.
- Explicitly uses a `.nvmrc` to mark the node version of `14`. We'll want to move this to a modern version (`20`) soon.
- Removes `eslines` from `npm lint-js`. [`eslines` is an Automattic utility](https://github.com/Automattic/eslines) that seemed to be used to ignore linting errors also in the `master` branch, but was throwing errors and blocking tests. As it's close to 3 years out of date, I just dropped the usage and allowed `eslint` tests to fail. We'll come back to these very soon to `--fix`, ignore, and manually fix the remaining errors.

### CODE REVIEW

**Comment by alecgeatches** [comment]
End to end tests are now passing! See the last run: https://github.com/Automattic/Edit-Flow/actions/runs/9165713334/job/25199719325

The `lint-js` task has been moved to run after jest and end-to-end tests. We'll come back to address the tons of linting warnings and errors very soon.

**Comment by alecgeatches** [comment]
Hello @rebeccahum! We're doing some refactorings starting with fixing end-to-end tests in GitHub Actions and a PHP version bump. Please take a look! We'll plan to do a new plugin release once we're done with modernization work.

**Review by ingeniumed — APPROVED** [review]
Would it be worth switching the branch it's going to, to be a release branch? That way, once we wrap up our modernization changes we can make a single merge of that into the main branch and cut the release. There's going to be another breaking change after this so figured do it one go.

**Comment by alecgeatches** [comment]
@ingeniumed I'm going to merge this into a new `develop` branch. Thank you!

**Pull request merged**
