### PR TITLE
Use taxonomy when checking for term existence

### PR DESCRIPTION
**Pull request by shadyvb**

### CODE REVIEW

**Comment by cojennin** [comment]
@shadyvb did you verify that this patch does not cause a regression based on [this comment](https://github.com/Automattic/Edit-Flow/pull/362/files#diff-228291de10e40133681b1ff8414a9a54R768)?

Could you provide a a test and before/after of the expected behavior? A test would help with verifying functionality and a before/after would help with setting expectations for new behavior.

First thoughts: seems like it might cause some headache if folks have to deal with automatically created slugs they don't have control over (and they aren't able to predict what they slug will end up looking like)

**Comment by cojennin** [comment]
Looked into this a bit more. Looks like it was discussed in #82 but closed as wontfix. Also mentioned in the [support forum](https://wordpress.org/support/topic/plugin-edit-flow-problems-with-custom-statuses/). Still not sure why these checks weren't originally scoped to a taxonomy. The comments around this code (as I mentioned in #324) are why I'm hesitant to make this change.

**Comment by shadyvb** [comment]
@cojennin I'm having hard time understanding why this might not be needed, went through all the comments and references you posted, but still can't think of a solid reason why not to fix it.

I don't think the support forum comment about the missing posts assigned to a `draft` tag is related to the proposed fix, that `term_exist` call worked around the issue of colliding terms, but did not really fix it. ie: It deprives the user from the privilege that WordPress already provides, having similar terms under different taxonomies, and IMHO for no real reason, specially with a four line fix.

The patch does not cause a regression in my tests, and if you have a reason to think there might be in any scenario, let me know and I'll be happy to help write some tests to eliminate any concerns. I just can't think of any related to this specific change ( not the support forum ticket ).

**Comment by cojennin** [comment]
> I'm having hard time understanding why this might not be needed, went through all the comments and references you posted, but still can't think of a solid reason why not to fix it.

Same, which is why I'm confused. Seems strange to add the `term_exists` check but not include the taxonomy. Would think excluding it would be done for a specific reason. But maybe that's just overthinking it.

I'd like to get a minor version of Edit Flow out tomorrow or Friday with a few bug fixes, localization improvements. After that I'll merge this in.

Does seem strange that it was never brought up as a solution to #82 (I wish I remember why it wasn't brought up as an easy fix...)

**Comment by cojennin** [comment]
Alrighty, Edit Flow v0.8.2 is out so going to merge this one in! Thanks for the patch!

**Pull request merged**
