### PR TITLE
Russian translation thorough update and correction

### PR DESCRIPTION
**Pull request by achumakov**
The existing translation is 2 years behind. Also, deviations from WordPress codex are corrected. A publishing workflow terminology common in Russia is implemented.

### CODE REVIEW

**Comment by cojennin** [comment]
These seem like two distinct patches. Can you split them up? One patch for just the fixes to the Russian translation and one patch for all the internationalization fixes would be great.

**Comment by cojennin** [comment]
Any updates on this? Would be great to get it into the next version of Edit Flow!

**Comment by achumakov** [comment]
Sorry I missed your previous e-mail.Could look at this day after tomorrow, thank you!                                                                                                                                                                                                                                                                                                                                        Отправлено с моего смартфона BlackBerry 10.                                                                                                                                                                                                                От: Connor JenningsОтправлено: вторник, 17 мая 2016 г., 0:29Кому: Automattic/Edit-FlowОтветить: Automattic/Edit-FlowКопия: Alexey Chumakov; AuthorТема: Re: [Automattic/Edit-Flow] Russian translation thorough update and correction (#308)Any updates on this? Would be great to get it into the next version of Edit Flow!

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by cojennin** [comment]
Still working on this @achumakov?

**Comment by cojennin** [comment]
Just checking back. Think you'll have some time to finish this up?

**Comment by achumakov** [comment]
Sorry for VERY long silence — I had some reasons for it ;(

Sure I have some time now. Sorry I see you've already released some 
updates, but if that's possible I could submit all the updates soon.

01.09.2016 6:22, Connor Jennings пишет:

**Comment by cojennin** [comment]
@achumakov Not a problem! Would be great to see these updates in the next release.

I would split this pull request into two patches, one for the internationalization fixes and one for the translation improvements. Should be able to merge them in without much hassle, patch already looks pretty good :)

**Comment by achumakov** [comment]
This pull request is superceded by two separate ones (one for translation, one for i18n issues).

**Pull request closed without merging**
