### PR TITLE
Filter post_preview_link for a viewable preview link

### LINKED ISSUE #513: Post Previews are broken on custom post statuses
1) Create post without publishing and save with extended post status of anything but "Draft" (e.g. "Assigned")
2) Hit "Preview" button
3) You will be redirected to a URL of the post with `?p=19&preview=true&preview_id=19&preview_nonce=0ae11b01ec` where `preview_nonce` should not be appended to URL
4) View from another account with the appropriate permissions such as administrator and you will receive error message `Sorry, you are not allowed to preview drafts.`

Not sure if related to #344.

### PR DESCRIPTION
**Pull request by rebeccahum**
This PR resolves #513.  Since the check (https://github.com/WordPress/WordPress/blob/cf3fa9f7c8038447303eea1fbd3636c5fece28cd/wp-admin/includes/post.php#L1808) in `wp_create_post_autosave()` fails because an autosave is not present for unpublished posts saved with custom statuses, `preview_nonce` gets added onto the preview link.  This also piggybacks off the logic in `wp_create_autosave()` to check if this is a personal preview: https://github.com/WordPress/WordPress/blob/cf3fa9f7c8038447303eea1fbd3636c5fece28cd/wp-admin/includes/post.php#L1791

### CODE REVIEW

**Comment by valdezm** [comment]
The personal preview conditional isn't working, our site no longer has preview capabilities since preview_nonce never appears. We have to revert this plugin back in order to have our Editors the ability to preview their work before publishing.

This block of code is unconditionally removing preview_nonce:
	public function fix_preview_link_part_three( $preview_link, $query_args ) {
		if ( $autosave = wp_get_post_autosave( $query_args->ID, $query_args->post_author ) ) {
		    foreach ( array_intersect( array_keys( _wp_post_revision_fields( $query_args ) ), array_keys( _wp_post_revision_fields( $autosave ) ) ) as $field ) {
		        if ( normalize_whitespace( $query_args->$field ) != normalize_whitespace( $autosave->$field ) ) {
		        	// Pass through, it's a personal preview.
		            return $preview_link;
		        }
		   }
		}
		return remove_query_arg( [ 'preview_nonce' ], $preview_link );  
	}

Please advise

**Comment by rebeccahum** [comment]
@valdezm Can you please provide steps on how to reproduce?

**Comment by valdezm** [comment]
I am waiting on authroization from the company to dig any deeper in to this. But since the update, the filter is unconditionally removing preview_nonce resulting in the Preview to no longer work.

I'll update in 24 hours, should know by then.

**Comment by justmahito** [comment]
Hi @rebeccahum, this fix breaks the preview functionality for the cases when the user is not the author of the post, but has appropriate permissions for editing others posts: the issue occurs because WP creates autosave for the current user and in your commit you check autosave for the post author and not for the current user.

Regards,
Maryia

**Comment by ashkanghadimi** [comment]
Hi
we have the same issue with our published post that preview is not working for theme. some of our posts have wp_nonce in preview link and those are showing the changes, but some of the others don't have wp_nonce and they are not showing the last changes in preview and we have to update (publish) to see the changes. It happens since some months ago with recent updates of edit-flow.

**Comment by rebeccahum** [comment]
@ashkanghadimi Hi! Do you have any steps on reproducing this on a clean WP install?

**Comment by ashkanghadimi** [comment]
1-Make a post with sample text
2-publish it
3-make a change in published post and click on preview button.

You probably can not see the changes after publishing this post.

**Pull request merged**
