### PR TITLE
Fix custom status error with Gutenberg 7.2+

### PR DESCRIPTION
**Pull request by cojennin**
A fix for #583. Continuing to break the rules, but for a good cause. 

Props to @ryelle for tracking this down

## Steps to Test

1. With Gutenberg 7.2 or 7.3
2. With the custom status module active
3. Try to edit a draft post
4. Editor should not crash

### CODE REVIEW

**Comment by ryelle** [comment]
Loading, editing, and saving a draft works, but after the draft finishes saving, the button reverts to "save draft" 

Screen Shot 2020-01-23 at 11 16 32 AMScreen Shot 2020-01-23 at 11 16 22 AM

I'm also seeing a crash with a custom status ("assigned")— this time, the post loads fine, but crashes when I try to save it. The error is the same: 

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Comment by WPprodigy** [comment]
Hmm, so GB is changes the markup pretty drastically during the saving states. Perhaps utilizing more of the selectors could help here, like `select( 'core/editor' ).isSavingPost()`. I'll see what I can find.

Also noting that https://github.com/WordPress/gutenberg/pull/12517 is another issue to watch as a better way to solve this.

**Comment by WPprodigy** [comment]
Ugh, and there is also https://github.com/WordPress/gutenberg/issues/17632 that would help here (was closed in favor of https://github.com/WordPress/gutenberg/issues/13413, though it is a bit different IMO).

**Comment by WPprodigy** [comment]
Tried a different approach in https://github.com/Automattic/Edit-Flow/pull/585

**Comment by cojennin** [comment]
Closing in favor of #585

**Pull request closed without merging**
