### PR TITLE
fix typo for module messages

### PR DESCRIPTION
**Pull request by natebot**
Fixing typo in reference to $this->module->message array, as reported in #313

### CODE REVIEW

**Comment by Warpsmith** [comment]
Are you sure it isn't supposed to be an 's' at the end?
i.e. $this->module->messages

**Comment by cojennin** [comment]
Doesn't look like there's a message for `term-error` in [custom-status.php](https://github.com/natebot/Edit-Flow/blob/typo-fix-for-die-messages/modules/custom-status/custom-status.php#L48). 

Also doesn't look like there's a message for `term-error` or `usergroup-error` in [editorial-metadata.php](https://github.com/natebot/Edit-Flow/blob/typo-fix-for-die-messages/modules/editorial-metadata/editorial-metadata.php#L56).

If I trigger the case that results in [this wp_die](https://github.com/Automattic/Edit-Flow/pull/316/files#diff-228291de10e40133681b1ff8414a9a54R811) I get the following exception `Undefined index: term-error`.

Think the messaging just needs to be provided for `term-error` and `usergroup-error` in their respective locations in [editorial-metadata.php](https://github.com/natebot/Edit-Flow/blob/typo-fix-for-die-messages/modules/editorial-metadata/editorial-metadata.php#L56) and [custom-status.php](https://github.com/natebot/Edit-Flow/blob/typo-fix-for-die-messages/modules/custom-status/custom-status.php#L48). Do you have some time to add that to this PR? Open to suggestions on what that messaging should say.

**Comment by cojennin** [comment]
Ah, read over #313 again and saw you already caught the missing messages @natebot. Let me know if you have some time to add that messaging into this PR!

**Comment by cojennin** [comment]
Hrm, looking at this again. Seems like in both cases in [user-groups.php](https://github.com/Automattic/Edit-Flow/pull/316/files#diff-4e59b27536156258f08652c20b30bed0L347) it should [`usergroup-missing`](https://github.com/Automattic/Edit-Flow/blob/master/modules/user-groups/user-groups.php#L55), right? Looks like it's a check to make sure the user group exists.

Same with [custom-status.php](https://github.com/Automattic/Edit-Flow/pull/316/files#diff-228291de10e40133681b1ff8414a9a54L810). Looks like its checking to see if the custom status exists, and should therefore be [`status-missing`](https://github.com/Automattic/Edit-Flow/blob/master/modules/custom-status/custom-status.php#L50).

Also same with [editorial-metadata.php](https://github.com/Automattic/Edit-Flow/pull/316/files#diff-b05bfc08ddd74a98f2c13380e04b9f04L1092). All those checks look to be checking for whether the editorial metadata exists, and should use [`term-missing`](https://github.com/Automattic/Edit-Flow/blob/master/modules/editorial-metadata/editorial-metadata.php#L59). 

Thoughts?

**Comment by cojennin** [comment]
@natebot Awesome, thanks!

**Comment by cojennin** [comment]
Let this one slip by me, my bad. Just wanted to check if you're still interested in updating this PR!

**Comment by cojennin** [comment]
@natedog Let me know if you've got the time to finish this one out, would be great to see it get merged in. If not no worries! I don't mind doing the grunt work to finish this one out. Don't want your work to go to waste!

**Comment by cojennin** [comment]
@natebot solid! Give me a minute just to trigger some of these error cases and I think we'll be good to go!

**Comment by cojennin** [comment]
Gave it a quick test and it looks quite dope. Some of these methods could probably do with some automated testing, but that's a PR for another day.

Thanks for finishing this out, much appreciated!

**Pull request merged**
